const TYPE_COLORS = {
  fire:       { bg: "from-red-700 to-orange-900",    text: "text-red-400",     abbr: "F"  },
  water:      { bg: "from-blue-600 to-blue-900",     text: "text-blue-400",    abbr: "W"  },
  grass:      { bg: "from-green-600 to-emerald-900", text: "text-green-400",   abbr: "G"  },
  electric:   { bg: "from-yellow-500 to-amber-800",  text: "text-yellow-400",  abbr: "L"  },
  psychic:    { bg: "from-purple-600 to-purple-900", text: "text-purple-400",  abbr: "P"  },
  fighting:   { bg: "from-red-800 to-red-950",       text: "text-orange-300",  abbr: "FG" },
  dark:       { bg: "from-gray-700 to-gray-950",     text: "text-gray-400",    abbr: "D"  },
  steel:      { bg: "from-slate-500 to-slate-800",   text: "text-slate-300",   abbr: "M"  },
  fairy:      { bg: "from-pink-500 to-rose-800",     text: "text-pink-400",    abbr: "Y"  },
  dragon:     { bg: "from-indigo-600 to-violet-950", text: "text-indigo-400",  abbr: "N"  },
  normal:     { bg: "from-slate-500 to-slate-700",   text: "text-gray-300",    abbr: "C"  },
  colorless:  { bg: "from-slate-500 to-slate-700",   text: "text-gray-300",    abbr: "C"  },
};

const SAMPLE_CARDS = [
  { name: "Charizard EX", card_type: "pokemon", hp: 330, energy_type: "fire", stage: "ex", rarity: "ultra_rare", set_name: "Obsidian Flames", attack1_name: "Burning Dark", attack1_damage: 180, attack1_cost: 3, attack2_name: "Inferno Reign", attack2_damage: 330, attack2_cost: 5, weakness: "water", retreat_cost: 3 },
  { name: "Pikachu VMAX", card_type: "pokemon", hp: 310, energy_type: "electric", stage: "vmax", rarity: "ultra_rare", set_name: "Vivid Voltage", attack1_name: "Thunder Bolt", attack1_damage: 120, attack1_cost: 2, attack2_name: "G-Max Volt Crash", attack2_damage: 270, attack2_cost: 4, weakness: "fighting", retreat_cost: 2 },
  { name: "Mewtwo VSTAR", card_type: "pokemon", hp: 280, energy_type: "psychic", stage: "vstar", rarity: "ultra_rare", set_name: "Pokemon GO", attack1_name: "Psy Purge", attack1_damage: 90, attack1_cost: 2, attack2_name: "Star Raid", attack2_damage: 220, attack2_cost: 3, weakness: "dark", retreat_cost: 2 },
  { name: "Blastoise", card_type: "pokemon", hp: 180, energy_type: "water", stage: "stage2", rarity: "holo_rare", set_name: "Base Set", attack1_name: "Hydro Pump", attack1_damage: 60, attack1_cost: 3, attack2_name: "Rain Dance", attack2_damage: 0, attack2_cost: 1, weakness: "electric", retreat_cost: 3 },
  { name: "Venusaur", card_type: "pokemon", hp: 190, energy_type: "grass", stage: "stage2", rarity: "holo_rare", set_name: "Base Set", attack1_name: "Solar Beam", attack1_damage: 80, attack1_cost: 4, weakness: "fire", retreat_cost: 2 },
  { name: "Gengar EX", card_type: "pokemon", hp: 260, energy_type: "psychic", stage: "ex", rarity: "ultra_rare", set_name: "Paldea Evolved", attack1_name: "Shadow Claw", attack1_damage: 100, attack1_cost: 2, attack2_name: "Phantom Dive", attack2_damage: 200, attack2_cost: 3, weakness: "dark", retreat_cost: 1 },
  { name: "Lucario VSTAR", card_type: "pokemon", hp: 270, energy_type: "fighting", stage: "vstar", rarity: "ultra_rare", set_name: "Brilliant Stars", attack1_name: "Aura Sphere", attack1_damage: 70, attack1_cost: 1, attack2_name: "Fighting Knuckle", attack2_damage: 200, attack2_cost: 3, weakness: "psychic", retreat_cost: 2 },
  { name: "Umbreon VMAX", card_type: "pokemon", hp: 310, energy_type: "dark", stage: "vmax", rarity: "secret_rare", set_name: "Evolving Skies", attack1_name: "Dark Signal", attack1_damage: 0, attack1_cost: 1, attack2_name: "Max Darkness", attack2_damage: 160, attack2_cost: 3, weakness: "grass", retreat_cost: 2 },
  { name: "Gardevoir EX", card_type: "pokemon", hp: 310, energy_type: "psychic", stage: "ex", rarity: "ultra_rare", set_name: "Scarlet & Violet", attack1_name: "Psychic Embrace", attack1_damage: 0, attack1_cost: 1, attack2_name: "Miracle Force", attack2_damage: 190, attack2_cost: 3, weakness: "steel", retreat_cost: 2 },
  { name: "Rayquaza VMAX", card_type: "pokemon", hp: 320, energy_type: "dragon", stage: "vmax", rarity: "secret_rare", set_name: "Evolving Skies", attack1_name: "Azure Pulse", attack1_damage: 80, attack1_cost: 1, attack2_name: "Max Burst", attack2_damage: 200, attack2_cost: 3, weakness: "none", retreat_cost: 2 },
  { name: "Mew VMAX", card_type: "pokemon", hp: 310, energy_type: "psychic", stage: "vmax", rarity: "secret_rare", set_name: "Fusion Strike", attack1_name: "Cross Fusion Strike", attack1_damage: 0, attack1_cost: 2, attack2_name: "Max Miracle", attack2_damage: 130, attack2_cost: 2, weakness: "dark", retreat_cost: 0 },
  { name: "Arceus VSTAR", card_type: "pokemon", hp: 280, energy_type: "colorless", stage: "vstar", rarity: "ultra_rare", set_name: "Brilliant Stars", attack1_name: "Trinity Nova", attack1_damage: 200, attack1_cost: 3, attack2_name: "Starbirth", attack2_damage: 0, attack2_cost: 0, weakness: "fighting", retreat_cost: 2 },
  { name: "Eevee", card_type: "pokemon", hp: 60, energy_type: "colorless", stage: "basic", rarity: "common", set_name: "Evolving Skies", attack1_name: "Tackle", attack1_damage: 20, attack1_cost: 1, weakness: "fighting", retreat_cost: 1 },
  { name: "Charmander", card_type: "pokemon", hp: 70, energy_type: "fire", stage: "basic", rarity: "common", set_name: "Base Set", attack1_name: "Scratch", attack1_damage: 10, attack1_cost: 1, attack2_name: "Ember", attack2_damage: 30, attack2_cost: 2, weakness: "water", retreat_cost: 1 },
  { name: "Squirtle", card_type: "pokemon", hp: 60, energy_type: "water", stage: "basic", rarity: "common", set_name: "Base Set", attack1_name: "Bubble", attack1_damage: 10, attack1_cost: 1, attack2_name: "Withdraw", attack2_damage: 0, attack2_cost: 1, weakness: "electric", retreat_cost: 1 },
  { name: "Bulbasaur", card_type: "pokemon", hp: 70, energy_type: "grass", stage: "basic", rarity: "common", set_name: "Base Set", attack1_name: "Vine Whip", attack1_damage: 10, attack1_cost: 1, attack2_name: "Leech Seed", attack2_damage: 20, attack2_cost: 2, weakness: "fire", retreat_cost: 1 },
  { name: "Dragonite EX", card_type: "pokemon", hp: 330, energy_type: "dragon", stage: "ex", rarity: "full_art", set_name: "Obsidian Flames", attack1_name: "Dragon Claw", attack1_damage: 140, attack1_cost: 3, attack2_name: "Hyperbeam", attack2_damage: 250, attack2_cost: 5, weakness: "none", retreat_cost: 3 },
  { name: "Sylveon VMAX", card_type: "pokemon", hp: 310, energy_type: "psychic", stage: "vmax", rarity: "ultra_rare", set_name: "Evolving Skies", attack1_name: "Precious Touch", attack1_damage: 60, attack1_cost: 1, attack2_name: "Max Harmony", attack2_damage: 160, attack2_cost: 3, weakness: "steel", retreat_cost: 2 },
  { name: "Magikarp", card_type: "pokemon", hp: 30, energy_type: "water", stage: "basic", rarity: "common", set_name: "Base Set", attack1_name: "Splash", attack1_damage: 10, attack1_cost: 1, weakness: "electric", retreat_cost: 1 },
  { name: "Gyarados EX", card_type: "pokemon", hp: 340, energy_type: "water", stage: "ex", rarity: "ultra_rare", set_name: "Paldea Evolved", attack1_name: "Tyrannical Tail", attack1_damage: 180, attack1_cost: 3, attack2_name: "Rampaging Whirlpool", attack2_damage: 300, attack2_cost: 5, weakness: "electric", retreat_cost: 4 },
  { name: "Professor's Research", card_type: "trainer", rarity: "uncommon", set_name: "Scarlet & Violet", description: "Discard your hand and draw 7 cards." },
  { name: "Boss's Orders", card_type: "trainer", rarity: "rare", set_name: "Rebel Clash", description: "Switch 1 of your opponent's Benched Pokemon with their Active Pokemon." },
  { name: "Ultra Ball", card_type: "trainer", rarity: "uncommon", set_name: "Sun & Moon", description: "Discard 2 cards from your hand. Search your deck for a Pokemon and put it into your hand." },
  { name: "Rare Candy", card_type: "trainer", rarity: "uncommon", set_name: "Scarlet & Violet", description: "Choose 1 of your Basic Pokemon in play. Search your deck for a Stage 2 card that evolves from that Pokemon and put it onto that Pokemon to evolve it." },
  { name: "Switch", card_type: "trainer", rarity: "common", set_name: "Base Set", description: "Switch your Active Pokemon with 1 of your Benched Pokemon." },
  { name: "Nest Ball", card_type: "trainer", rarity: "common", set_name: "Sun & Moon", description: "Search your deck for a Basic Pokemon and put it onto your Bench." },
  { name: "Battle VIP Pass", card_type: "trainer", rarity: "uncommon", set_name: "Fusion Strike", description: "You can only use this card during your first turn. Search your deck for up to 2 Basic Pokemon and put them onto your Bench." },
  { name: "Iono", card_type: "trainer", rarity: "rare", set_name: "Paldea Evolved", description: "Each player shuffles their hand into their deck and draws a card for each of their remaining Prize cards." },
  { name: "Fire Energy", card_type: "energy", energy_type: "fire", rarity: "common", set_name: "Base Set" },
  { name: "Water Energy", card_type: "energy", energy_type: "water", rarity: "common", set_name: "Base Set" },
  { name: "Grass Energy", card_type: "energy", energy_type: "grass", rarity: "common", set_name: "Base Set" },
  { name: "Electric Energy", card_type: "energy", energy_type: "electric", rarity: "common", set_name: "Base Set" },
  { name: "Psychic Energy", card_type: "energy", energy_type: "psychic", rarity: "common", set_name: "Base Set" },
  { name: "Fighting Energy", card_type: "energy", energy_type: "fighting", rarity: "common", set_name: "Base Set" },
  { name: "Dark Energy", card_type: "energy", energy_type: "dark", rarity: "common", set_name: "Base Set" },
  { name: "Steel Energy", card_type: "energy", energy_type: "steel", rarity: "common", set_name: "Base Set" },
  { name: "Dragon Energy", card_type: "energy", energy_type: "dragon", rarity: "rare", set_name: "Evolving Skies", description: "Provides 2 energy: 1 Fire and 1 Water." },
  { name: "Double Turbo Energy", card_type: "energy", energy_type: "colorless", rarity: "uncommon", set_name: "Brilliant Stars", description: "Provides 2 Colorless energy. Attacks do 20 less damage." },
];

export { TYPE_COLORS, SAMPLE_CARDS };
