// =============================================================
// CARD MECHANIC CONFIGS — persists per-card mechanic chains built
// in MechanicBuilder.jsx and registers them with the engine on
// boot. Each config attaches one or more PRIMITIVES + GUARDS to
// a specific (cardId, attackName) pair; the engine's existing
// `attack.custom_mechanics` hook then runs them after base damage.
// =============================================================

import { registerCustomMechanic } from "@/lib/customMechanics";
import { runMechanicConfig, getPrimitiveById, getGuardById } from "@/lib/mechanicPrimitives";
import { getAutoMechanicMap } from "@/lib/releaseSync";

const STORAGE_KEY = "tcg_card_mechanic_configs_v1";

function canStore() {
  return typeof window !== "undefined" && typeof window.localStorage !== "undefined";
}

function readAll() {
  if (!canStore()) return {};
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function writeAll(map) {
  if (!canStore()) return;
  try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(map)); }
  catch (err) { console.warn("Failed to persist card mechanic configs", err); }
}

function makeKey(cardId, attackName) {
  return `${cardId}::${attackName || "*"}`;
}

export function listConfigs() {
  return readAll();
}

export function getConfig(cardId, attackName) {
  return readAll()[makeKey(cardId, attackName)] || null;
}

export function getConfigsForCard(cardId) {
  const all = readAll();
  return Object.values(all).filter((c) => c.cardId === cardId);
}

export function saveConfig(config) {
  if (!config?.cardId) throw new Error("config.cardId is required");
  const all = readAll();
  const key = makeKey(config.cardId, config.attackName);
  all[key] = {
    cardId: config.cardId,
    cardName: config.cardName || "",
    attackName: config.attackName || "*",
    primitives: Array.isArray(config.primitives) ? config.primitives : [],
    updatedAt: new Date().toISOString(),
    enabled: config.enabled !== false,
  };
  writeAll(all);
  registerConfigWithEngine(all[key]);
  return all[key];
}

export function deleteConfig(cardId, attackName) {
  const all = readAll();
  const key = makeKey(cardId, attackName);
  delete all[key];
  writeAll(all);
}

// Engine integration ------------------------------------------------------
// Each config is registered as a single mechanic id derived from the card+
// attack identity. The runtime composes the primitives + guards via
// `runMechanicConfig`, returning a mutated game state plus any extraLog.
export function mechanicIdFor(cardId, attackName) {
  return `card-mechanic:${cardId}:${attackName || "*"}`;
}

export function registerConfigWithEngine(config) {
  if (!config?.enabled) return;
  const id = mechanicIdFor(config.cardId, config.attackName);
  registerCustomMechanic(id, (gs, pk /* opts */) => {
    // Clone so primitives can mutate freely without reaching back into the
    // shared engine state; the engine merges back what we return.
    const cloned = JSON.parse(JSON.stringify(gs));
    // Inherit the running bonusDamage tally — when an attack is wired up to
    // both an exact-match and a wildcard config, performAttack invokes us
    // twice in sequence with the previous mechanic's `bonusDamage` already
    // merged onto `gs`. Without this, the second pass would reset the
    // accumulator to 0 and the first pass's `+N` would silently disappear.
    const carry = Number(cloned.bonusDamage || 0);
    const next = runMechanicConfig(cloned, pk, config, { bonusDamage: carry }) || cloned;
    const log = (next._mechanicLog || []).join(" ");
    delete next._mechanicLog;
    return { ...next, extraLog: log };
  });
}

export function registerAllSavedCardMechanics() {
  const all = readAll();
  for (const config of Object.values(all)) registerConfigWithEngine(config);
}

// Code-generation --------------------------------------------------------
// Renders an executable JS string equivalent to the saved config — useful
// for the preview pane in the Mechanic Builder UI and for export-to-file.
export function generateCodeForConfig(config) {
  if (!config?.cardId) return "";
  const id = mechanicIdFor(config.cardId, config.attackName);
  const lines = [];
  lines.push(`// Auto-generated by Mechanic Builder.`);
  lines.push(`// Card: ${config.cardName || config.cardId}`);
  lines.push(`// Attack: ${config.attackName || "(any)"}`);
  lines.push(`registerCustomMechanic(${JSON.stringify(id)}, (gs, pk) => {`);
  lines.push(`  const s = JSON.parse(JSON.stringify(gs));`);
  lines.push(`  const log = [];`);
  lines.push(`  const opp = (k) => k === "player1" ? "player2" : "player1";`);
  for (const entry of config.primitives || []) {
    const prim = getPrimitiveById(entry.id);
    if (!prim) continue;
    const guards = (entry.guards || []).map((g) => {
      const guardDef = getGuardById(g.id);
      if (!guardDef) return null;
      return `  // guard: ${guardDef.label} ${JSON.stringify(g.params || {})}`;
    }).filter(Boolean);
    lines.push("");
    lines.push(`  // → ${prim.label} ${JSON.stringify(entry.params || {})}`);
    if (guards.length) lines.push(...guards);
    lines.push(`  // (runtime executes via runMechanicConfig — see mechanicPrimitives.js)`);
  }
  lines.push("");
  lines.push(`  return { ...s, extraLog: log.join(" ") };`);
  lines.push(`});`);
  return lines.join("\n");
}

// Hydration helper -------------------------------------------------------
// Given an attack definition (after API normalisation), check if a saved
// config matches by attack name and inject a `custom_mechanics` reference
// so the engine fires it. This is called from `enrichAttacksWithMechanics`
// in cardCatalog.
export function injectCustomMechanicsForAttack(cardId, cardName, attack) {
  if (!attack?.name) return attack;
  const exact = getConfig(cardId, attack.name);
  const wildcard = getConfig(cardId, "*");
  const match = exact || wildcard;
  const existing = Array.isArray(attack.custom_mechanics) ? attack.custom_mechanics : [];

  let next = { ...attack, custom_mechanics: [...existing] };

  if (match?.enabled) {
    const id = mechanicIdFor(match.cardId, match.attackName);
    if (!next.custom_mechanics.some((m) => m?.id === id)) {
      next.custom_mechanics.push({ id, opts: {} });
    }
    next._customMechanicCardId = cardId;
    next._customMechanicCardName = cardName;
  }

  const autoMap = getAutoMechanicMap();
  const autoEntries = autoMap[`${cardId}:${attack.name}`] || [];
  for (const entry of autoEntries) {
    if (!entry?.id) continue;
    if (next.custom_mechanics.some((m) => m?.id === entry.id && JSON.stringify(m?.opts || {}) === JSON.stringify(entry?.opts || {}))) continue;
    next.custom_mechanics.push({ id: entry.id, opts: entry.opts || {} });
  }

  if (!next.custom_mechanics.length) return attack;
  return next;
}
