import React, { useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Check,
  CheckCircle2,
  Code,
  Copy,
  Cpu,
  Download,
  Eye,
  PackagePlus,
  Play,
  Sparkles,
  Trash2,
  X,
  Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/use-toast";
import BottomNav from "@/components/tcg/BottomNav";
import PageHeader from "@/components/tcg/PageHeader";
import { fetchCatalogCards } from "@/lib/cardCatalog";
import {
  deleteMechanic,
  heuristicMechanicsForAttacks,
  listMechanics,
  registerSavedMechanics,
  saveMechanic,
  validateMechanic,
} from "@/lib/mechanicLibrary";

const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_KEY_STORAGE = "tcg_mechanic_studio_groq_key_v1";
const MODES = [
  {
    id: "heuristic",
    label: "Heuristic (local)",
    icon: Cpu,
    desc: "No API key — infers common patterns from attack text.",
  },
  {
    id: "groq",
    label: "Groq LLM",
    icon: Sparkles,
    desc: "Best quality. Bring your own Groq API key.",
  },
];

function extractAttacks(cards) {
  const attacks = [];
  for (const card of cards) {
    if (card.attack1_name) {
      attacks.push({
        card: card.name,
        attack: card.attack1_name,
        damage: card.attack1_damage,
        cost: card.attack1_cost,
        description: card.attack1_description || "",
      });
    }
    if (card.attack2_name) {
      attacks.push({
        card: card.name,
        attack: card.attack2_name,
        damage: card.attack2_damage,
        cost: card.attack2_cost,
        description: card.attack2_description || "",
      });
    }
  }
  return attacks.filter((a) => a.description || /flip|draw|attach|heal|damage|poison|burn|paralyz|sleep|confus|recoil/i.test(a.attack || ""));
}

function parseGroqCodeBlocks(rawCode) {
  return rawCode
    .split("```javascript")
    .slice(1)
    .map((block) => block.split("```")[0].trim())
    .filter((b) => b.length > 0 && b.includes("registerCustomMechanic"))
    .map((code, idx) => {
      const match = code.match(/registerCustomMechanic\(\s*["']([^"']+)["']/);
      return {
        id: match ? match[1] : `groq-mechanic-${idx}`,
        name: match ? match[1] : `Groq Mechanic ${idx + 1}`,
        description: "Generated by Groq",
        source: "groq",
        code,
        tags: ["groq"],
      };
    });
}

export default function MechanicStudio() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const logRef = useRef(null);

  const [provider, setProvider] = useState("heuristic");
  const [groqKey, setGroqKey] = useState(() => {
    if (typeof window === "undefined") return "";
    return window.localStorage.getItem(GROQ_KEY_STORAGE) || "";
  });
  const [remember, setRemember] = useState(false);
  const [cardsPerBatch, setCardsPerBatch] = useState(80);
  const [stage, setStage] = useState("idle");
  const [running, setRunning] = useState(false);

  const [scannedCards, setScannedCards] = useState([]);
  const [extractedAttacks, setExtractedAttacks] = useState([]);
  const [generated, setGenerated] = useState([]);
  const [selected, setSelected] = useState(null);
  const [logs, setLogs] = useState([]);
  const [library, setLibrary] = useState(() => listMechanics());
  const [validationByMechanic, setValidationByMechanic] = useState({});

  const appendLog = (msg, type = "info", details = "") => {
    const entry = {
      id: `${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      msg,
      type,
      details,
      time: new Date().toLocaleTimeString(),
    };
    setLogs((prev) => [...prev.slice(-80), entry]);
    queueMicrotask(() => {
      if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight;
    });
  };

  useEffect(() => {
    if (!remember) return;
    if (typeof window === "undefined") return;
    if (groqKey) window.localStorage.setItem(GROQ_KEY_STORAGE, groqKey);
  }, [groqKey, remember]);

  const persistLibrary = () => setLibrary(listMechanics());

  const runHeuristic = async () => {
    setStage("scanning");
    appendLog("Fetching card catalog…", "info");
    const { cards } = await fetchCatalogCards({
      search: "",
      filter: "all",
      page: 1,
      pageSize: cardsPerBatch,
    });
    setScannedCards(cards);
    appendLog(`Scanned ${cards.length} cards`, "ok");

    setStage("extracting");
    const attacks = extractAttacks(cards);
    setExtractedAttacks(attacks);
    appendLog(`Extracted ${attacks.length} candidate attacks`, "ok");

    setStage("generating");
    const mechanics = heuristicMechanicsForAttacks(attacks);
    setGenerated(mechanics);
    appendLog(`Heuristic generated ${mechanics.length} mechanics`, "ok");
    setStage("review");
  };

  const runGroq = async () => {
    if (!groqKey.trim()) {
      toast({ title: "API key required", description: "Paste a Groq key or switch to heuristic mode." });
      return;
    }
    setStage("scanning");
    appendLog("Fetching card catalog…", "info");
    const { cards } = await fetchCatalogCards({
      search: "",
      filter: "all",
      page: 1,
      pageSize: Math.min(cardsPerBatch, 80),
    });
    setScannedCards(cards);
    const attacks = extractAttacks(cards);
    setExtractedAttacks(attacks);
    appendLog(`Scanned ${cards.length} cards, ${attacks.length} attacks`, "ok");

    setStage("generating");
    appendLog("Calling Groq…", "info");

    const prompt = `Analyze these Pokémon TCG card attacks and identify UNIQUE mechanics (not: basic damage, coin flip, draw, discard, heal, apply status).

Attacks:
${attacks
  .slice(0, 20)
  .map(
    (a, i) =>
      `${i + 1}. [${a.card}] "${a.attack}" (${a.damage} dmg) - ${a.description || "standard attack"}`
  )
  .join("\n")}

For EACH unique mechanic found, output ONLY valid JavaScript in this format:

\`\`\`javascript
registerCustomMechanic("mechanic-id", (gs, pk, opts) => {
  let updated = JSON.parse(JSON.stringify(gs));
  // Your mechanic logic here
  return { ...updated, extraLog: "Description" };
});
\`\`\`

NO explanations, NO markdown, ONLY code blocks.`;

    const response = await fetch(GROQ_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${groqKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "llama-3.3-70b-versatile",
        messages: [
          { role: "system", content: "You are a code generator. Output ONLY valid JavaScript code. No explanations." },
          { role: "user", content: prompt },
        ],
        temperature: 0.2,
        max_tokens: 3000,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      appendLog(`Groq error: ${response.status}`, "error", err.slice(0, 200));
      setStage("review");
      return;
    }

    const data = await response.json();
    const rawCode = data.choices?.[0]?.message?.content || "";
    const mechanics = parseGroqCodeBlocks(rawCode);
    setGenerated(mechanics);
    appendLog(`Groq produced ${mechanics.length} mechanics`, "ok");
    setStage("review");
  };

  const startPipeline = async () => {
    if (running) return;
    setRunning(true);
    setScannedCards([]);
    setExtractedAttacks([]);
    setGenerated([]);
    setValidationByMechanic({});
    setSelected(null);
    setLogs([]);
    try {
      if (provider === "groq") {
        await runGroq();
      } else {
        await runHeuristic();
      }
      toast({ title: "Pipeline complete", description: "Review + test mechanics below." });
    } catch (err) {
      appendLog(`Error: ${err.message}`, "error");
      toast({ title: "Pipeline failed", description: err.message });
    } finally {
      setRunning(false);
    }
  };

  const validateOne = (mech) => {
    const result = validateMechanic(mech.code);
    setValidationByMechanic((prev) => ({ ...prev, [mech.id]: result }));
    if (result.ok) {
      appendLog(`✓ ${mech.name || mech.id} passed validation (${result.durationMs}ms)`, "ok");
      if (result.warnings.length) {
        appendLog(`  warnings: ${result.warnings.join("; ")}`, "warn");
      }
    } else {
      appendLog(`✗ ${mech.name || mech.id}: ${result.errors.join("; ")}`, "error");
    }
    return result;
  };

  const validateAll = () => {
    for (const mech of generated) {
      validateOne(mech);
    }
  };

  const installMechanic = (mech) => {
    const result = validationByMechanic[mech.id] || validateOne(mech);
    if (!result.ok) {
      toast({ title: "Cannot install", description: "Fix validation errors first." });
      return;
    }
    saveMechanic({ ...mech, installed: true });
    registerSavedMechanics();
    persistLibrary();
    toast({ title: "Installed", description: `${mech.name || mech.id} is now active in battles.` });
  };

  const saveDraft = (mech) => {
    saveMechanic({ ...mech, installed: false });
    persistLibrary();
    toast({ title: "Saved", description: "Mechanic stored without installing." });
  };

  const removeFromLibrary = (id) => {
    deleteMechanic(id);
    persistLibrary();
    // Re-register so uninstalled is no longer active
    registerSavedMechanics();
    toast({ title: "Removed" });
  };

  const downloadAll = () => {
    const code = generated.map((m) => m.code).join("\n\n");
    const blob = new Blob([code], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "mechanics.js";
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(generated.map((m) => m.code).join("\n\n"));
      toast({ title: "Copied" });
    } catch {
      toast({ title: "Copy failed" });
    }
  };

  const selectedValidation = selected ? validationByMechanic[selected.id] : null;

  const stats = useMemo(
    () => [
      { label: "Cards", value: scannedCards.length },
      { label: "Attacks", value: extractedAttacks.length },
      { label: "Generated", value: generated.length },
      { label: "Installed", value: library.filter((m) => m.installed).length },
    ],
    [scannedCards, extractedAttacks, generated, library]
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20 pb-24">
      <div className="sticky top-0 z-20 bg-background/95 backdrop-blur border-b border-border">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between gap-3">
          <button
            onClick={() => navigate("/admin")}
            className="flex items-center gap-1.5 text-muted-foreground hover:text-foreground transition-colors font-body text-sm"
          >
            <ArrowLeft className="w-4 h-4" /> Admin
          </button>
          <div className="flex items-center gap-3">
            <p className="font-display font-bold text-lg">Mechanic Studio</p>
            <Badge variant="secondary" className="font-body capitalize">
              {stage}
            </Badge>
          </div>
          <div className="flex gap-2">
            {generated.length > 0 && (
              <Button variant="outline" size="sm" className="font-body gap-1.5" onClick={validateAll}>
                <CheckCircle2 className="w-3.5 h-3.5" /> Validate all
              </Button>
            )}
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-6 space-y-6">
        <PageHeader
          title="MECHANIC STUDIO"
          subtitle="Generate, validate and install custom battle mechanics"
        />

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="space-y-6"
          >
            <div className="rounded-2xl border border-border bg-card p-5 space-y-4">
              <h2 className="font-display font-bold text-lg">Configuration</h2>

              <div className="grid grid-cols-1 gap-2">
                {MODES.map((option) => {
                  const Icon = option.icon;
                  const active = provider === option.id;
                  return (
                    <button
                      key={option.id}
                      onClick={() => setProvider(option.id)}
                      className={`rounded-xl border p-3 text-left transition-colors ${
                        active
                          ? "border-primary bg-primary/10"
                          : "border-border bg-background hover:bg-secondary"
                      }`}
                    >
                      <div className="flex items-center gap-2">
                        <Icon className="w-4 h-4" />
                        <p className="font-body font-semibold text-sm">{option.label}</p>
                      </div>
                      <p className="text-[11px] text-muted-foreground mt-1 font-body">{option.desc}</p>
                    </button>
                  );
                })}
              </div>

              {provider === "groq" && (
                <div>
                  <label className="text-xs font-body text-muted-foreground uppercase tracking-widest mb-1.5 block">
                    Groq API Key
                  </label>
                  <input
                    type="password"
                    value={groqKey}
                    onChange={(e) => setGroqKey(e.target.value)}
                    disabled={running}
                    placeholder="gsk_..."
                    className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm font-mono text-foreground disabled:opacity-50"
                  />
                  <label className="mt-2 inline-flex items-center gap-2 text-[11px] text-muted-foreground font-body cursor-pointer">
                    <input
                      type="checkbox"
                      checked={remember}
                      onChange={(e) => setRemember(e.target.checked)}
                      className="accent-primary"
                    />
                    Remember in this browser (localStorage)
                  </label>
                </div>
              )}

              <div>
                <label className="text-xs font-body text-muted-foreground uppercase tracking-widest mb-1.5 block">
                  Cards to scan
                </label>
                <input
                  type="number"
                  value={cardsPerBatch}
                  onChange={(e) => setCardsPerBatch(Number(e.target.value))}
                  disabled={running}
                  min="10"
                  max="200"
                  className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm font-mono text-foreground disabled:opacity-50"
                />
              </div>

              <Button onClick={startPipeline} disabled={running} className="w-full font-body gap-2">
                {running ? <Zap className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4" />}
                {running ? "Running…" : "Start pipeline"}
              </Button>
            </div>

            <div className="grid grid-cols-2 gap-2">
              {stats.map((stat) => (
                <div
                  key={stat.label}
                  className="rounded-xl border border-border bg-secondary/40 p-3 text-center"
                >
                  <p className="text-2xl font-display font-black text-primary">{stat.value}</p>
                  <p className="text-xs font-body text-muted-foreground mt-1">{stat.label}</p>
                </div>
              ))}
            </div>

            <div className="rounded-2xl border border-border bg-card p-5 space-y-3">
              <div className="flex items-center justify-between gap-2">
                <h3 className="font-display font-bold text-base">Installed library</h3>
                <Badge variant="outline">{library.length}</Badge>
              </div>
              {library.length === 0 ? (
                <p className="text-xs font-body text-muted-foreground">
                  Saved mechanics appear here and auto-register on page load.
                </p>
              ) : (
                <div className="space-y-2 max-h-60 overflow-y-auto">
                  {library.map((mech) => (
                    <div key={mech.id} className="rounded-lg border border-border bg-background p-2.5">
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                          <p className="text-sm font-body font-semibold truncate">{mech.name || mech.id}</p>
                          <p className="text-[11px] text-muted-foreground font-body truncate">
                            {mech.source} · {mech.installed ? "installed" : "draft"}
                          </p>
                        </div>
                        <button
                          onClick={() => removeFromLibrary(mech.id)}
                          className="text-muted-foreground hover:text-red-400 p-1"
                          title="Remove"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6"
          >
            <div className="rounded-2xl border border-border bg-card p-5 space-y-3">
              <h2 className="font-display font-bold text-lg flex items-center gap-2">
                <Eye className="w-5 h-5 text-blue-400" /> Generated mechanics
              </h2>
              {generated.length === 0 ? (
                <p className="text-xs font-body text-muted-foreground">
                  Run the pipeline to see heuristic or LLM-generated mechanics here.
                </p>
              ) : (
                <div className="space-y-2 max-h-[420px] overflow-y-auto">
                  {generated.map((mech) => {
                    const v = validationByMechanic[mech.id];
                    return (
                      <button
                        key={mech.id}
                        onClick={() => setSelected(mech)}
                        className={`w-full p-3 rounded-lg text-left transition-colors border ${
                          selected?.id === mech.id
                            ? "border-primary bg-primary/10"
                            : "border-border bg-background hover:bg-secondary"
                        }`}
                      >
                        <div className="flex items-center justify-between gap-2">
                          <div className="min-w-0">
                            <p className="text-sm font-body font-semibold truncate">{mech.name}</p>
                            <p className="text-[11px] text-muted-foreground font-body truncate">
                              {mech.source} · {mech.id}
                            </p>
                          </div>
                          {v ? (
                            v.ok ? (
                              <Check className="w-4 h-4 text-emerald-500 flex-shrink-0" />
                            ) : (
                              <X className="w-4 h-4 text-red-500 flex-shrink-0" />
                            )
                          ) : (
                            <Badge variant="outline" className="text-[10px]">new</Badge>
                          )}
                        </div>
                      </button>
                    );
                  })}
                </div>
              )}
            </div>

            <div
              ref={logRef}
              className="rounded-2xl border border-border bg-card p-4 h-48 overflow-y-auto space-y-1"
            >
              {logs.length === 0 ? (
                <p className="text-xs font-body text-muted-foreground">
                  Activity log — scan, extraction, validation and install events appear here.
                </p>
              ) : (
                logs.map((log) => (
                  <div
                    key={log.id}
                    className={`text-xs font-mono flex items-start gap-2 ${
                      log.type === "error"
                        ? "text-red-400"
                        : log.type === "warn"
                        ? "text-amber-400"
                        : log.type === "ok"
                        ? "text-emerald-400"
                        : "text-muted-foreground"
                    }`}
                  >
                    <span className="text-[10px] text-muted-foreground flex-shrink-0">[{log.time}]</span>
                    <div>
                      <div>{log.msg}</div>
                      {log.details && <div className="text-[10px] opacity-60 mt-0.5">{log.details}</div>}
                    </div>
                  </div>
                ))
              )}
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="space-y-6"
          >
            {selected ? (
              <div className="rounded-2xl border border-border bg-card p-5 space-y-4">
                <div className="flex items-center justify-between gap-2">
                  <div className="min-w-0">
                    <h3 className="font-display font-bold text-base truncate">{selected.name}</h3>
                    <p className="text-[11px] text-muted-foreground font-body truncate">{selected.id}</p>
                  </div>
                  <Button size="sm" className="font-body gap-1.5" onClick={() => validateOne(selected)}>
                    <Play className="w-3 h-3" /> Test
                  </Button>
                </div>

                <div className="bg-secondary/60 rounded-lg p-3 overflow-x-auto max-h-64 overflow-y-auto">
                  <pre className="font-mono text-xs text-foreground/80 whitespace-pre-wrap break-words">
                    {selected.code}
                  </pre>
                </div>

                {selectedValidation && (
                  <div
                    className={`rounded-lg border p-3 text-xs font-body space-y-1 ${
                      selectedValidation.ok
                        ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300"
                        : "border-red-500/30 bg-red-500/10 text-red-300"
                    }`}
                  >
                    <p className="font-semibold">
                      {selectedValidation.ok
                        ? `Validated in ${selectedValidation.durationMs}ms`
                        : "Validation failed"}
                    </p>
                    {selectedValidation.errors.map((err, i) => (
                      <p key={`err-${i}`} className="opacity-90">• {err}</p>
                    ))}
                    {selectedValidation.warnings.map((warn, i) => (
                      <p key={`warn-${i}`} className="opacity-80">⚠ {warn}</p>
                    ))}
                  </div>
                )}

                <div className="grid grid-cols-2 gap-2">
                  <Button
                    onClick={() => installMechanic(selected)}
                    className="font-body gap-1.5"
                    disabled={selectedValidation && !selectedValidation.ok}
                  >
                    <PackagePlus className="w-3.5 h-3.5" /> Install
                  </Button>
                  <Button
                    onClick={() => saveDraft(selected)}
                    variant="outline"
                    className="font-body gap-1.5"
                  >
                    <Code className="w-3.5 h-3.5" /> Save draft
                  </Button>
                </div>

                <Button
                  onClick={() => {
                    navigator.clipboard.writeText(selected.code);
                    toast({ title: "Copied" });
                  }}
                  variant="ghost"
                  size="sm"
                  className="w-full font-body gap-1.5"
                >
                  <Copy className="w-3.5 h-3.5" /> Copy code
                </Button>
              </div>
            ) : (
              <div className="rounded-2xl border border-border bg-card p-6 flex items-center justify-center h-64">
                <p className="text-muted-foreground text-sm font-body text-center">
                  Select a mechanic to test, install, or export.
                </p>
              </div>
            )}

            {generated.length > 0 && (
              <div className="rounded-2xl border border-primary/30 bg-primary/5 p-5 space-y-3">
                <h3 className="font-display font-bold text-base">Batch actions</h3>
                <Button onClick={validateAll} className="w-full font-body gap-2" variant="outline">
                  <CheckCircle2 className="w-4 h-4" /> Validate all
                </Button>
                <Button
                  onClick={() => {
                    let installed = 0;
                    for (const mech of generated) {
                      const result = validationByMechanic[mech.id] || validateOne(mech);
                      if (result.ok) {
                        saveMechanic({ ...mech, installed: true });
                        installed += 1;
                      }
                    }
                    registerSavedMechanics();
                    persistLibrary();
                    toast({ title: `Installed ${installed} mechanics` });
                  }}
                  className="w-full font-body gap-2"
                >
                  <PackagePlus className="w-4 h-4" /> Install all valid
                </Button>
                <Button onClick={downloadAll} variant="outline" className="w-full font-body gap-2">
                  <Download className="w-4 h-4" /> Download .js
                </Button>
                <Button onClick={copyAll} variant="outline" className="w-full font-body gap-2">
                  <Copy className="w-4 h-4" /> Copy all
                </Button>
              </div>
            )}
          </motion.div>
        </div>
      </div>

      <BottomNav />
    </div>
  );
}
